version: '3'

services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data

  mq:
    image: rabbitmq:3.8.2-alpine

  app:
    image: app
    build: .
    command: wait-for-it db:5432 -- hypercorn --bind 0.0.0.0:8000 app.asgi:application
    ports:
      - 8000:8000
    depends_on:
      - db
      - mq
    volumes:
      - ./app:/app
